### ISSUE TITLE
Github page not found

### ISSUE THREAD

**Issue by PixsaOJ** [CodingGarden/entropychat.app#1]
### Issue

When I start both, server and client and try to log in, I put credentials and click sign in. It returns GitHub 404 page not found. No errors in electron console or terminal.

**Comment by w3cj** [comment]
You might be missing the oauth client id and secret. I added some setup instructions here: https://github.com/CodingGarden/entropychat.app#server-setup

Let me know if this works.

**Comment by PixsaOJ** [comment]
File `.env.example` is missing, what are the variables?

**Comment by PixsaOJ** [comment]
I found `server/config` but it is not using `.env`. I can update readme file.

**Comment by PixsaOJ** [comment]
After adding GitHub secrets;

![2020-05-17 08-47-28](https://user-images.githubusercontent.com/12684017/82136241-77860700-981c-11ea-825e-986bedb2e133.gif)

**Comment by w3cj** [comment]
The sample .env file is here:
https://github.com/CodingGarden/entropychat.app/blob/master/server/.env.sample

You need to make sure that the vue app is running on port 8080. The server only sends the login token to that origin:
https://github.com/CodingGarden/entropychat.app/blob/master/server/public/index.html#L39

You could try debugging the client in the browser with: `npm run serve`

**Comment by PixsaOJ** [comment]
It worked ! ✨🎉🎉
