### ISSUE TITLE
EntropyChat Github Team

### ISSUE THREAD

**Issue by w3cj** [CodingGarden/entropychat.app#16]
I created this team: https://github.com/orgs/CodingGarden/teams/entropychat
Leave a comment here if you would like to be added.

**Comment by PixsaOJ** [comment]
Yes pliz

**Comment by oskygh** [comment]
yes

**Comment by ivoencarnacao** [comment]
I would also like to join, if possible!

**Comment by infi** [comment]
:wave:

**Comment by CallumChaney** [comment]
I would love to join

**Comment by w3cj** [comment]
I just found out, granting team permission would allow anyone to create repos under the CodingGarden organization. I don't want that, so I'll look into creating a separate organization/team for this.
